stages:
  - build
  - push

Build Docker image:
  stage: build
  image: ruby:latest
  before_script:
    - gem install bundler
    - bundle install
  script:
    - bundle exec jekyll build
  artifacts:
    paths:
      - _site

Push Docker image:
  stage: push
  only:
    - master
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
  script:
    - docker build -t $QUAY_REPOSITORY:latest $QUAY_REPOSITORY:ci-$CI_COMMIT_SHA .
    - docker push $QUAY_REPOSITORY:latest $QUAY_REPOSITORY:ci-$CI_COMMIT_SHA
