stages:
  - build
  - push

Build Docker image:
  stage: build
  image: ruby:latest
  before_script:
    - gem install bundler
    - bundle install
  script:
    - bundle exec jekyll build
  artifacts:
    paths:
      - _site

quay.io:
  stage: push
  only:
    - master
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - echo "$QUAY_PASSWORD" | docker login -u $QUAY_USER --password-stdin https://quay.io
  script:
    - docker build -t $QUAY_REPOSITORY:latest $QUAY_REPOSITORY:ci-$CI_COMMIT_SHA .
    - docker push $QUAY_REPOSITORY:latest $QUAY_REPOSITORY:ci-$CI_COMMIT_SHA

registry.gitlab.com:
  stage: push
  only:
    - master
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:ci-$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:ci-$CI_COMMIT_SHA
