# site settings
title: Friendly GNU/Linux Thread/Website
email: tyil@scriptkitties.church
description: > # this means to ignore newlines until "baseurl:"
  Nondescript
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fglt.nl" # the base hostname & protocol for your site

# build settings
markdown: redcarpet
redcarpet:
  extensions: [
    "tables",
    "autolink",
    "strikethrough",
    "space_after_headers",
    "with_toc_data",
    "fenced_code_blocks"
  ]

# custom collections
collections:
  guides:
    output: true

