# site settings
title: Friendly GNU/Linux Thread/Website
author: tyil
email: tyil@scriptkitties.church
description: > # this means to ignore newlines until "baseurl:"
  The Friendly GNU/Linux Thread/Website, for all your GNU+Linux questions
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fglt.nl" # the base hostname & protocol for your site

# build settings
markdown: kramdown
redcarpet:
  extensions: [
    "tables",
    "autolink",
    "strikethrough",
    "space_after_headers",
    "with_toc_data",
    "fenced_code_blocks"
  ]

# custom collections
collections:
  agora:
    output: true
  guides:
    output: true
  pages:
    output: true
  quotes:
    output: true

# page defaults
defaults:
  - scope:
      path: ""
    values:  # Set front matter variables
      layout: "default"  # Default appears to be no layout…

# Pages for jekyll-optional-front-matter to render.
include:
  - README.md

plugins:
  - jekyll-optional-front-matter
